<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Nikhil-LP" failures="1" tests="9" name="api.Test.Contacts_CRUD" time="16.047" errors="0" timestamp="2025-01-19T14:09:51 IST" skipped="4">
  <testcase classname="api.Test.Contacts_CRUD" name="createUser" time="1.966"/>
  <testcase classname="api.Test.Contacts_CRUD" name="editContactDeatils" time="2.189"/>
  <testcase classname="api.Test.Contacts_CRUD" name="viewContactAfterUpdate" time="2.031"/>
  <testcase classname="api.Test.Contacts_CRUD" name="deleteContact" time="2.054"/>
  <testcase classname="api.Test.Contacts_CRUD" name="viewContactAfterDelete" time="1.890">
    <skipped/>
  </testcase> <!-- viewContactAfterDelete -->
  <testcase classname="api.Test.Contacts_CRUD" name="viewContactAfterDelete" time="1.900">
    <failure message="The following asserts failed:
	expected [206] but found [200],
	expected [206] but found [200],
	expected [206] but found [200],
	expected [206] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [206] but found [200],
expected [206] but found [200],
expected [206] but found [200],
expected [206] but found [200]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at api.Test.Contacts_CRUD.viewContactAfterDelete(Contacts_CRUD.java:217)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- viewContactAfterDelete -->
  <testcase classname="api.Test.Contacts_CRUD" name="viewContactAfterDelete" time="1.982">
    <skipped/>
  </testcase> <!-- viewContactAfterDelete -->
  <testcase classname="api.Test.Contacts_CRUD" name="viewContactAfterDelete" time="2.035">
    <skipped/>
  </testcase> <!-- viewContactAfterDelete -->
  <testcase classname="api.Test.Contacts_CRUD" name="viewContact">
    <skipped/>
  </testcase> <!-- viewContact -->
</testsuite> <!-- api.Test.Contacts_CRUD -->
